version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: samadhan
      POSTGRES_PASSWORD: samadhan
      POSTGRES_DB: samadhan
    ports:
      - "5432:5432"